[package]
name = "compass-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
nucleo-matcher.workspace = true
rayon = "1"

[[bench]]
name = "ranking_experiments"
harness = false

[dev-dependencies]
criterion = { version = "0.5" }
proptest.workspace = true
