[package]
name = "compass-worker-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
compass-oauth-store = { path = "../compass-oauth-store" }
compass-local-storage = { path = "../compass-local-storage" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
compass-db = { path = "../compass-db" }
compass-sqlcipher-sys = { path = "../compass-sqlcipher-sys" }
tempfile.workspace = true
