
// generated by vicinae figura codegen - do not edit manually

interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	send(data: string): void;
}

export class RpcTransport {
	constructor(private readonly transport: ITransport) { }

	emit(method: string, params: Record<string, any>): void {
		this.sendMessage({ jsonrpc: '2.0', method, params });
	}

	reply(id: number, result: any) {
		this.sendMessage({ jsonrpc: '2.0', id, result });
	}

	private sendMessage(msg: JsonRpcMessage) {
		this.transport.send(JSON.stringify(msg));
	}
};

export type CommandMode = 'View' | 'NoView';

export type CommandEnv = 'Development' | 'Production';

export type LaunchType = 'User' | 'Background' | 'CommandLine';

export type Capabilities = {
	browserExtension: boolean;
	windowManagement: boolean;
	wallpaper: boolean;
	fileSearch: boolean;
}

export type LaunchEventData = {
	extension_name: string;
	command_name: string;
	mode: CommandMode;
	entrypoint: string;
	asset_path: string;
	support_path: string;
	preferenceValues: any;
	argumentValues: any;
	launch_context: any;
	is_raycast: boolean;
	owner_or_author_name: string;
	launch_type: LaunchType;
	capabilities: Capabilities;
	fallbackText?: string;
	cwd?: string;
	extension_id?: string;
}

export abstract class LifecycleService {
	constructor(private readonly rpc: RpcTransport) {}
	abstract launch(data: LaunchEventData): Promise <boolean>;
	abstract shutdown(): Promise <boolean>;
	abstract send_message(msg: string): Promise <boolean>;
emit_extension_message(msg: string) {
	this.rpc.emit("Lifecycle/extension_message", { msg});
}emit_unload_requested() {
	this.rpc.emit("Lifecycle/unload_requested", { });
}
}
export class Server {
	constructor(private readonly rpc: RpcTransport, readonly Lifecycle: LifecycleService) {
}


	route(raw: string) {
		const msg = JSON.parse(raw) as JsonRpcMessage;

		// request
		if (msg.id !== undefined && msg.method && msg.params) {
			const id = msg.id;

			switch (msg.method) {
	case "Lifecycle/launch":	return this.Lifecycle.launch(msg.params.data).then((r) => this.rpc.reply(id, r))
case "Lifecycle/shutdown":	return this.Lifecycle.shutdown().then((r) => this.rpc.reply(id, r))
case "Lifecycle/send_message":	return this.Lifecycle.send_message(msg.params.msg).then((r) => this.rpc.reply(id, r))
default: throw new Error(`No handler for method ${msg.method}`)
}
}
}
}