
// generated by vicinae figura codegen - do not edit manually

interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	send(data: string): void;
}

type EventSubscription = {
	unsubscribe: () => void;
};

export class RpcTransport {
	constructor(private readonly transport: ITransport) { }

	dispatchMessage(data: string) {
		const msg = JSON.parse(data) as JsonRpcMessage;

		if (msg.id !== undefined) {
			const handler = this.requestMap.get(msg.id);

			if (handler) {
				if (msg.error) handler.reject(msg.error);
				else handler.resolve(msg.result);
				this.requestMap.delete(msg.id);
			}
		}
		if (msg.id === undefined && msg.method) {
			for (const cb of this.handlers.get(msg.method) ?? []) {
				cb(msg.params);
			}
		}
	}

	request<T>(method: string, params: Record<string, any>): Promise<T> {
		const id = this.id++;
		const promise = new Promise<T>((resolve, reject) => {
			this.requestMap.set(id, { resolve: (msg) => resolve(msg as T), reject });
		});

		this.sendMessage({ jsonrpc: '2.0', id, method, params });

		return promise;
	}

	subscribe(method: string, cb: (result: any) => void): EventSubscription {
		const handlers = this.handlers.get(method);

		if (handlers) handlers.push(cb);
		else this.handlers.set(method, [cb]);

		return {
			unsubscribe: () => {
				const handlers = this.handlers.get(method);

				if (handlers) {
					handlers.splice(handlers.indexOf(cb), 1);
				}
			},
		};
	}

	private sendMessage(msg: JsonRpcMessage) {
		this.transport.send(JSON.stringify(msg));
	}


	private id = 1;
	private requestMap = new Map<number, { resolve: (value: any) => void, reject: (error: any) => void }>;
	private handlers = new Map<string, Array<(result: any) => void>>;
};

export type CommandMode = 'View' | 'NoView';

export type CommandEnv = 'Development' | 'Production';

export type LaunchType = 'User' | 'Background' | 'CommandLine';

export type Capabilities = {
	browserExtension: boolean;
	windowManagement: boolean;
	wallpaper: boolean;
	fileSearch: boolean;
}

export type LaunchEventData = {
	extension_name: string;
	command_name: string;
	mode: CommandMode;
	entrypoint: string;
	asset_path: string;
	support_path: string;
	preferenceValues: any;
	argumentValues: any;
	launch_context: any;
	is_raycast: boolean;
	owner_or_author_name: string;
	launch_type: LaunchType;
	capabilities: Capabilities;
	fallbackText?: string;
	cwd?: string;
	extension_id?: string;
}

class LifecycleService {
	constructor(private readonly transport: RpcTransport) {}

	launch(data: LaunchEventData): Promise<boolean> {
		return this.transport.request("Lifecycle/launch", { data});	
	}

	shutdown(): Promise<boolean> {
		return this.transport.request("Lifecycle/shutdown", { });	
	}

	send_message(msg: string): Promise<boolean> {
		return this.transport.request("Lifecycle/send_message", { msg});	
	}

	extension_message(handler: (msg: string) => void): EventSubscription {
		return this.transport.subscribe("Lifecycle/extension_message", (msg) => handler(msg.msg))
	}
	unload_requested(handler: () => void): EventSubscription {
		return this.transport.subscribe("Lifecycle/unload_requested", (msg) => handler())
	}
}

export class Client {
	constructor(private readonly transport: RpcTransport) {
		this.Lifecycle = new LifecycleService(this.transport);
	}

  	route(msg: string): void { this.transport.dispatchMessage(msg); }
  	Lifecycle: LifecycleService;

}
