
// generated by vicinae figura codegen - do not edit manually

interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	send(data: string): void;
}

export class RpcTransport {
	constructor(private readonly transport: ITransport) { }

	emit(method: string, params: Record<string, any>): void {
		this.sendMessage({ jsonrpc: '2.0', method, params });
	}

	reply(id: number, result: any) {
		this.sendMessage({ jsonrpc: '2.0', id, result });
	}

	private sendMessage(msg: JsonRpcMessage) {
		this.transport.send(JSON.stringify(msg));
	}
};

export type CommandMode = 'View' | 'NoView';

export type CommandEnv = 'Development' | 'Production';

export type LaunchType = 'User' | 'Background' | 'CommandLine';

export type Capabilities = {
	browserExtension: boolean;
	windowManagement: boolean;
	wallpaper: boolean;
	fileSearch: boolean;
}

export type LoadOptions = {
	mode: CommandMode;
	env: CommandEnv;
	vicinae_path: string;
	entrypoint: string;
	is_raycast: boolean;
	command_name: string;
	extension_id: string;
	extension_name: string;
	owner_or_author_name: string;
	arguments: any;
	preferences: any;
	launch_context: any;
	launch_type: LaunchType;
	capabilities: Capabilities;
	fallbackText?: string;
	cwd?: string;
}

export type LoadResponse = {
	session_id: string;
}

export abstract class ManagerService {
	constructor(private readonly rpc: RpcTransport) {}
	abstract load(opts: LoadOptions): Promise <LoadResponse>;
	abstract unload(session_id: string): Promise <boolean>;
	abstract ready(session_id: string): Promise <boolean>;
	abstract messageExtension(session_id: string, payload: string): Promise <boolean>;
emit_extensionMessage(session_id: string, payload: string) {
	this.rpc.emit("Manager/extensionMessage", { session_id, payload});
}emit_extensionCrash(session_id: string, reason: string) {
	this.rpc.emit("Manager/extensionCrash", { session_id, reason});
}
}
export class Server {
	constructor(private readonly rpc: RpcTransport, readonly Manager: ManagerService) {
}


	route(raw: string) {
		const msg = JSON.parse(raw) as JsonRpcMessage;

		// request
		if (msg.id !== undefined && msg.method && msg.params) {
			const id = msg.id;

			switch (msg.method) {
	case "Manager/load":	return this.Manager.load(msg.params.opts).then((r) => this.rpc.reply(id, r))
case "Manager/unload":	return this.Manager.unload(msg.params.session_id).then((r) => this.rpc.reply(id, r))
case "Manager/ready":	return this.Manager.ready(msg.params.session_id).then((r) => this.rpc.reply(id, r))
case "Manager/messageExtension":	return this.Manager.messageExtension(msg.params.session_id, msg.params.payload).then((r) => this.rpc.reply(id, r))
default: throw new Error(`No handler for method ${msg.method}`)
}
}
}
}