[package]
name = "compass-oauth-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
compass-db = { path = "../compass-db" }
compass-sqlcipher-sys = { path = "../compass-sqlcipher-sys" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
