[package]
name = "vicinae"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "vicinae"
path = "src/lib.rs"

[[bin]]
name = "vicinae"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
compass-core.workspace = true
compass-ipc.workspace = true
compass-portals.workspace = true
compass-ui.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true }
tracing.workspace = true
tracing-subscriber.workspace = true
zbus.workspace = true
landlock.workspace = true
seccompiler.workspace = true
libc.workspace = true
tempfile.workspace = true

[dev-dependencies]
compass-testkit.workspace = true
tempfile = "3"
