//! The MIME type hierarchy, and walking it to find what opens a file.
//!
//! Ports the parent-chain half of `XdgAppDatabase::findAssociations`
//! (`src/server/src/services/app-service/xdg/xdg-app-database.cpp`), which the
//! C++ gets from `QMimeDatabase`. The association lookup for *one* type is
//! already in [`crate::mimeapps`]; what is here is the walk that asks about a
//! type's ancestors when nothing claims the type itself.
//!
//! Without it, a `.tar.gz` whose type is `application/x-compressed-tar` finds
//! nothing unless something registered for that exact name — even with an
//! archive manager installed that registered for `application/gzip`, which is
//! its parent.

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::path::{Path, PathBuf};

/// Where the shared MIME database keeps the subclass table, below a data
/// directory.
pub const SUBCLASSES_PATH: &str = "mime/subclasses";

/// The `child parent` table, indexed by child.
///
/// A type may have several parents, which is why this is a list and not one
/// entry: `application/x-compressed-tar` is both a `gzip` and, through it, a
/// `tar`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Subclasses {
    parents: BTreeMap<String, Vec<String>>,
}

impl Subclasses {
    /// Parse the shared MIME database's `subclasses` file.
    ///
    /// One `child parent` pair per line. A line with anything other than two
    /// fields is skipped rather than refused: the file is generated by
    /// `update-mime-database` from whatever packages installed, and one
    /// malformed line should not cost every association on the system.
    #[must_use]
    pub fn parse(data: &str) -> Self {
        let mut parents: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for line in data.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut fields = line.split_whitespace();
            let (Some(child), Some(parent), None) = (fields.next(), fields.next(), fields.next())
            else {
                continue;
            };
            let entry = parents.entry(child.to_owned()).or_default();
            if !entry.iter().any(|existing| existing == parent) {
                entry.push((*parent).to_owned());
            }
        }
        Self { parents }
    }

    /// Merge another table into this one.
    ///
    /// Later data directories add to earlier ones rather than replacing them,
    /// because each package ships its own types and the union is the
    /// hierarchy. Within a child, a parent already present is not repeated.
    pub fn merge(&mut self, other: Self) {
        for (child, parents) in other.parents {
            let entry = self.parents.entry(child).or_default();
            for parent in parents {
                if !entry.contains(&parent) {
                    entry.push(parent);
                }
            }
        }
    }

    /// Load and merge the table from every data directory that has one.
    #[must_use]
    pub fn load(data_dirs: &[PathBuf], read: impl Fn(&Path) -> Option<String>) -> Self {
        let mut merged = Self::default();
        for dir in data_dirs {
            if let Some(data) = read(&dir.join(SUBCLASSES_PATH)) {
                merged.merge(Self::parse(&data));
            }
        }
        merged
    }

    /// A type's immediate parents.
    #[must_use]
    pub fn parents_of(&self, mime: &str) -> &[String] {
        self.parents.get(mime).map_or(&[], Vec::as_slice)
    }

    /// Whether the table knows anything at all.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.parents.is_empty()
    }
}

/// Every type to ask about, nearest first.
///
/// A breadth-first walk, so a type's own associations are considered before
/// its parents' and a near ancestor before a distant one — which is what makes
/// a PDF reader registered for `application/pdf` beat one registered for
/// `application/octet-stream`.
///
/// # A divergence, declared in PARITY.md
///
/// The C++ keeps no record of which types it has already walked. A type
/// reachable by two routes is therefore visited twice — harmless, because the
/// association lookup deduplicates by application — but a **cycle in the
/// table loops forever**. `subclasses` is generated, so a cycle would be a bug
/// in `update-mime-database` or in a package's XML rather than something a
/// user writes; it is still a file on disk that this reads. This keeps a
/// visited set, which makes the walk terminate on any input and removes the
/// duplicate visits at the same time.
#[must_use]
pub fn ancestry(subclasses: &Subclasses, mime: &str) -> Vec<String> {
    let mut order = Vec::new();
    let mut seen = BTreeSet::new();
    let mut queue = VecDeque::new();

    queue.push_back(mime.to_owned());
    seen.insert(mime.to_owned());

    while let Some(current) = queue.pop_front() {
        for parent in subclasses.parents_of(&current) {
            if seen.insert(parent.clone()) {
                queue.push_back(parent.clone());
            }
        }
        order.push(current);
    }

    order
}

/// The applications that can open a type, best first.
///
/// Each type in the ancestry is asked in turn and its answers appended, with
/// anything already offered left out. An application that claims both a type
/// and its parent therefore appears once, in the position its *nearest* claim
/// earned — which is the one that says most about what it can actually do.
#[must_use]
pub fn openers_through_ancestry(
    subclasses: &Subclasses,
    mime: &str,
    openers_for: impl Fn(&str) -> Vec<String>,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for ancestor in ancestry(subclasses, mime) {
        for id in openers_for(&ancestor) {
            if !out.contains(&id) {
                out.push(id);
            }
        }
    }
    out
}

/// The application that opens a type by default.
///
/// The first of [`openers_through_ancestry`]. The C++ tries the lists' own
/// `Default Applications` for the exact type first and only then falls back to
/// the full walk; that ordering is already inside the per-type lookup, so
/// asking the ancestry in order gives the same answer with one code path
/// instead of two.
#[must_use]
pub fn default_opener_through_ancestry(
    subclasses: &Subclasses,
    mime: &str,
    openers_for: impl Fn(&str) -> Vec<String>,
) -> Option<String> {
    openers_through_ancestry(subclasses, mime, openers_for)
        .into_iter()
        .next()
}
