[package]
name = "compass-shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
include = ["src/**/*.rs", "dbus/*.xml", "Cargo.toml"]

[lints]
workspace = true

[dependencies]
zbus.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true
serde.workspace = true

[dev-dependencies]
tokio = { workspace = true }
roxmltree.workspace = true
