[package]
name = "compass-portals"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ashpd = { workspace = true, features = ["global_shortcuts", "open_uri", "file_chooser", "settings"] }
zbus.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true

[dev-dependencies]
serde.workspace = true
tokio = { workspace = true }
