[package]
name = "compass-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
compass-xdg.workspace = true
compass-search.workspace = true
compass-core.workspace = true

[[bin]]
name = "parity"
path = "src/parity.rs"
